<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GameShelf.Infrastructure</RootNamespace>
    <AssemblyName>GameShelf.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameShelf.Application\GameShelf.Application.csproj" />
    <ProjectReference Include="..\GameShelf.Domain\GameShelf.Domain.csproj" />
  </ItemGroup>

</Project>
